#==============================================================================
#D A make file to make the unit tests

# Add the executables here like exe/utest_Class_1.exe exe/utest_Class_2.exe
EXECUTABLES = exe/utest_primes.exe
INCLUDES = -I..
LIBS = ../lib/PrimeSieve.lib
# code to run tests like so ./exe/test_1.exe && ./exe/test_2.exe && ...
RUN_TESTS = ./exe/utest_primes.exe

include $(DROPBOX)/Coding/MakeFiles/cpp_utest.mk
# override varaibles here
